server:
  port: 1900
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    # 应用名称
    name: gateway-master
  cloud:
    gateway:
      discovery:
        locator:
          # 是否和服务注册与发现组件结合，设置为 true 后可以直接使用应用名称调用服务
          enabled: true
          lower-case-service-id: true
      # 路由（routes：路由，它由唯一标识（ID）、目标服务地址（uri）、一组断言（predicates）和一组过滤器组成（filters）。filters 不是必需参数。）
      routes:
      - id: test-id
        uri: https://www.cnblogs.com/ # lb://client-manage
#        order: -1
        predicates:
        - Path=/api2/**
        filters:
        - StripPrefix=1
        

eureka:
  client:
    service-url:
      defaultZone: http://172.17.32.58:8000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,bus-refresh,shutdown
  endpoint:
    shutdown:
      enabled: true #是否开启优雅停机
      shutdown-time: 30 #强制停机时间(默认60)
      shutdown-time-unit: SECONDS   #强制停机时间单位(默认SECONDS)
      health-wait-time: 10 #关闭前等待健康监测时间(默认10),即在请求shutdown接口时,会延时这个时间进行Shutdown操作
      health-wait-time-unit: SECONDS   #关闭前等待健康监测时间单位(默认SECONDS),即在请求shutdown接口时,会延时这个时间进行Shutdown操作
        
logging:
  level:
    root: info
